USE [e_pme_db_v2]
GO

/****** Object:  View [dbo].[dossier_view]    Script Date: 29/05/2020 06:17:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[dossier_view] 
AS
    SELECT 
      dbo.DOSSIER_ENTREPRISE.ID_DOSS,
      dbo.DOSSIER_ENTREPRISE.ID_UT,
      dbo.DOSSIER_ENTREPRISE.ID_VIL,
      dbo.DOSSIER_ENTREPRISE.ID_DOM,
      dbo.DOSSIER_ENTREPRISE.ID_ST_D,
      dbo.DOSSIER_ENTREPRISE.ID_REG,
      dbo.DOSSIER_ENTREPRISE.ID_TYP_ENT,
      dbo.DOSSIER_ENTREPRISE.ID_C_IMP,
      dbo.DOSSIER_ENTREPRISE.ID_CAT,
      dbo.DOSSIER_ENTREPRISE.NUM_DOSS,
      dbo.DOSSIER_ENTREPRISE.RAISON_SOCIAL,
      dbo.DOSSIER_ENTREPRISE.SIGLE,
      dbo.DOSSIER_ENTREPRISE.RCCM_DOSS,
      dbo.DOSSIER_ENTREPRISE.DATE_CREATION,
      dbo.DOSSIER_ENTREPRISE.CAPITAL_DOSS,
      dbo.DOSSIER_ENTREPRISE.SIEGE_SOCIAL_DOSS,
      dbo.DOSSIER_ENTREPRISE.ADRESS_POST,
      dbo.DOSSIER_ENTREPRISE.TELEPHONE_FIXE,
      dbo.DOSSIER_ENTREPRISE.TELEPHONE_MOBILE,
      dbo.DOSSIER_ENTREPRISE.SITE_WEB,
      dbo.DOSSIER_ENTREPRISE.EMAIL_DOSS,
      dbo.DOSSIER_ENTREPRISE.AUTRE_DOMAINE,
      dbo.DOSSIER_ENTREPRISE.DESCRIPTION,
      dbo.DOSSIER_ENTREPRISE.CMPT_CONTRUBUABLE,
      dbo.DOSSIER_ENTREPRISE.NUM_CNPS,
      dbo.DOSSIER_ENTREPRISE.NBR_EMP_DECL,
      dbo.DOSSIER_ENTREPRISE.NBR_EMP_PART,
      dbo.DOSSIER_ENTREPRISE.DATE_INSERT_DOSS,
      dbo.DOSSIER_ENTREPRISE.DATE_MODIF_DOSS,
      dbo.DOSSIER_ENTREPRISE.DEBUT_VALID,
      dbo.DOSSIER_ENTREPRISE.FIN_VALID,
      dbo.DOSSIER_ENTREPRISE.COMMENTAIRE,
      dbo.UTILISATEUR.ID_PRV,
      dbo.UTILISATEUR.CIVILITE_UT,
      dbo.UTILISATEUR.NOM_UT,
      dbo.UTILISATEUR.PRENOM_UT,
      dbo.UTILISATEUR.EMAIL_UT,
      dbo.UTILISATEUR.ETAT_UT,
      dbo.DIRIGEANT.ID_DRG,
      dbo.DIRIGEANT.CIVILITE_DRG,
      dbo.DIRIGEANT.NOM_DRG,
      dbo.DIRIGEANT.PRENOM_DRG,
      dbo.DIRIGEANT.DATE_NAISS_DRG,
      dbo.FONDATEUR.ID_FND,
      dbo.FONDATEUR.CIVILITE_FND,
      dbo.FONDATEUR.NOM_FND,
      dbo.FONDATEUR.PRENOM_FND,
      dbo.FONDATEUR.DATE_NAISS_FND,
      dbo.REGIME_IMPOSITION.DESIGNATION_REG,
      dbo.REGIME_IMPOSITION.COLOR_REG,
      dbo.ville_view.ID_RGN,
      dbo.ville_view.DESIGNATION_VIL,
      dbo.ville_view.DESIGNATION_RGN,
      dbo.ville_view.ID_DIST,
      dbo.ville_view.DESIGNATION_DIST,
      dbo.PERS_CT_DOSS.DATE_INSERT_PERS_CT_DOSS,
      dbo.PERS_CT_DOSS.CIVILITE_PERS_CT_DOSS,
      dbo.PERS_CT_DOSS.NOM_PERS_CT_DOSS,
      dbo.PERS_CT_DOSS.PRENOM_PERS_CT_DOSS,
      dbo.PERS_CT_DOSS.RESP_PERS_CT_DOSS,
      dbo.PERS_CT_DOSS.EMAIL_PERS_CT_DOSS,
      dbo.PERS_CT_DOSS.MOBILE_PERS_CT_DOSS,
      dbo.PERS_CT_DOSS.FIXE_PERS_CT_DOSS,
      dbo.PERS_CT_DOSS.ETAT_PERS_CT_DOSS,
      dbo.DOMAINE_ACTIVITE.DESIGNATION_DOM,
      dbo.STATUT_DOSSIER.DESIGNATION_ST_D,
      dbo.CATEGORIE_ENTREPRISE.DESIGNATION_CAT,
      dbo.CATEGORIE_ENTREPRISE.DESCRIPTION_CAT,
      dbo.CATEGORIE_ENTREPRISE.COLOR_CAT,
      dbo.CATEGORIE_ENTREPRISE.ETAT_CAT,
      dbo.centre_impot_view.ID_DIR_IMP,
      dbo.centre_impot_view.DESIGNATION_C_IMPO,
      dbo.centre_impot_view.DESIGNATION_DIR_IMP,
      dbo.TYPE_ENTREPRISE.DESIGNATION_TYP_ENT,
      dbo.TYPE_ENTREPRISE.COLOR_TYP_ENT,
      dbo.DOSSIER_ENTREPRISE.ETAT_DOSS,
      dbo.DOSSIER_ENTREPRISE.CODE_SSH,
      dbo.DOSSIER_ENTREPRISE.DATE_PRINT
    FROM
      dbo.DOSSIER_ENTREPRISE
      INNER JOIN dbo.UTILISATEUR ON (dbo.DOSSIER_ENTREPRISE.ID_UT = dbo.UTILISATEUR.ID_UT)
      INNER JOIN dbo.DIRIGEANT ON (dbo.DOSSIER_ENTREPRISE.ID_DOSS = dbo.DIRIGEANT.ID_DOSS)
      INNER JOIN dbo.FONDATEUR ON (dbo.DOSSIER_ENTREPRISE.ID_DOSS = dbo.FONDATEUR.ID_DOSS)
      INNER JOIN dbo.REGIME_IMPOSITION ON (dbo.DOSSIER_ENTREPRISE.ID_REG = dbo.REGIME_IMPOSITION.ID_REG)
      INNER JOIN dbo.ville_view ON (dbo.DOSSIER_ENTREPRISE.ID_VIL = dbo.ville_view.ID_VIL)
      INNER JOIN dbo.PERS_CT_DOSS ON (dbo.DOSSIER_ENTREPRISE.ID_DOSS = dbo.PERS_CT_DOSS.ID_DOSS)
      INNER JOIN dbo.DOMAINE_ACTIVITE ON (dbo.DOSSIER_ENTREPRISE.ID_DOM = dbo.DOMAINE_ACTIVITE.ID_DOM)
      INNER JOIN dbo.STATUT_DOSSIER ON (dbo.DOSSIER_ENTREPRISE.ID_ST_D = dbo.STATUT_DOSSIER.ID_ST_D)
      INNER JOIN dbo.CATEGORIE_ENTREPRISE ON (dbo.DOSSIER_ENTREPRISE.ID_CAT = dbo.CATEGORIE_ENTREPRISE.ID_CAT)
      INNER JOIN dbo.centre_impot_view ON (dbo.DOSSIER_ENTREPRISE.ID_C_IMP = dbo.centre_impot_view.ID_C_IMP)
      INNER JOIN dbo.TYPE_ENTREPRISE ON (dbo.DOSSIER_ENTREPRISE.ID_TYP_ENT = dbo.TYPE_ENTREPRISE.ID_TYP_ENT)
    WHERE
      dbo.UTILISATEUR.ETAT_UT <> -1 AND 
      dbo.CATEGORIE_ENTREPRISE.ETAT_CAT <> -1 AND 
      dbo.DOSSIER_ENTREPRISE.ETAT_DOSS = 1

GO


